#======================<开发环境配置>=========================
spring:
  datasource:
    #框架数据源配置
    frame:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      # 数据连接池其他配置  数据库连接池最大连接数=服务器核心数*2+1
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
    #业务-postgresql
    postgresql:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/yutu_pgis2_db
      username: postgres
      password: postgres
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
    #业务-oracle
    oracle:
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:ORCL
      username: REPORTSXYD
      password: REPORTSXYD
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
    #业务-sqlserver
    sqlserver:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;DatabaseName=EnvBAR_DB
      password: 1qaz2wsx
      username: dev
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000

  #redis设置
  redis:
    host: 127.0.0.1
    password: 1qaz2wsx
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: -1ms
        min-idle: 1
    timeout: 5000ms
